### ISSUE TITLE
进不了安装界面

### ISSUE THREAD

**Issue by cqq117** [Zephon-H/Hackintosh_Hase_t6-x5#1]
兄弟big sur用的是哪个版本的，我这儿到不了mac安装界面

**Comment by Zephon-H** [comment]
> 兄弟big sur用的是哪个版本的，我这儿到不了mac安装界面

忘了，好久没折腾了，应该是big sur刚开始的版本，现在可能又改了，你可以去远景上看看

**Comment by cqq117** [comment]
> > 兄弟big sur用的是哪个版本的，我这儿到不了mac安装界面
> 
> 忘了，好久没折腾了，应该是big sur刚开始的版本，现在可能又改了，你可以去远景上看看

最近搞这玩意儿，11和12死活跑不到安装界面，都是卡代码

**Comment by cqq117** [comment]
感谢兄弟的引导文件
